### ISSUE TITLE
Apply better filtering to TeamListView

### ISSUE THREAD

**Issue by andrewsosa** [FSU-ACM/Contest-Server#79]
TeamListView needs to make sure 

- [ ] only look for teams with an existing list of members (even if empty)
- [ ] only find teams with a division field

Basically ensure anything the template filters by is present, otherwise we start comparing things with None, and this breaks things. 

![image](https://user-images.githubusercontent.com/2829058/48303198-68125900-e4d5-11e8-965e-a69c493e3bb3.png)

**Comment by andrewsosa** [comment]
@manterolat didn't you already do this?

**Comment by manterolat** [comment]
You're right, it was fixed in #84! I'll close the issue.

**Comment by manterolat** [comment]
The current filter doesn't seem to catch all errors. We should check that:
1. `team_name` exists and is not empty
2. The team has at least one member (not worth showing otherwise, and catches the non-existing list error)
3. The team has an assigned division

This is meant to avoid issues when editing the models through the admin panel (adding/removing teams).
